### ISSUE TITLE
Support for multiple template files

### ISSUE THREAD

**Issue by FabianEmmes** [aixigo/freemarker-loader#6]
It would be great if freemarker-loader supported multiple template files. Currently, there is an option to specify one template, which is not sufficient in our use case.

**Comment by jpommerening** [comment]
That's right, currently we can only support one template file per loader configuration. 
We could make the `template` Parameter dynamic by using [loaderUtils.interpolateName()](https://github.com/webpack/loader-utils#interpolatename).

**Comment by jpommerening** [comment]
Fixed in `v0.4.0`

@FabianEmmes thanks for reporting this! For the case you mentioned in chat you can make use of the `[path]` placeholder to specify a template relative to the data file.
